### ISSUE TITLE
谢谢，我fork了你的项目，并修改了部分代码

### ISSUE THREAD

**Issue by letterb** [gtf35/easyShopping#1]
这是我fork后的项目地址：
https://github.com/letterb/caoTaobao
我加入了
1、双击返回键关闭应用
2、修正打开天猫页面后，重定向到intent://
3、删除app/build目录
4、修改部分配置
我想加入你的项目提交，但可惜没有权限，你有空可以看看。
再次感觉你的项目，让我的Android8.1手机可以运行淘宝，并且速度很快，而不用天天等淘宝更新，哈哈！

望学业进步！

**Comment by gtf35** [comment]
谢谢，今天刚刚看到你的issues，昨天刚填的天猫放intent://的坑。之前我一直没注意到。
build我是懒得删 /逃
GitHub我还不是特别会玩，有空研究研究。
我看了你的修改，好像并没有实现对intent://的处理。这个在网页加载前判断网址是不是http或https，是的话加载，不是的话抛弃就可以了(这个就是要唤醒客户端，真讨厌)。
在清理缓存那里，用的是clearCache(true)
通过查阅API文档得知：void clearCache (boolean includeDiskFiles)
参数是true的话除了清理RAM缓存之外还会清理disk的缓存，我个人觉得会造成返回之前的页面时间变长，可能会影响体验。
祝福已经收到
谢谢

祝工作顺利！

**Comment by gtf35** [comment]
我看了你的修改，好像并没有实现对intent://的处理。这个在网页加载前判断网址是不是http或https，是的话加载，不是的话抛弃就可以了(这个就是要唤醒客户端，真讨厌)。
在清理缓存那里，用的是clearCache(true)
通过查阅API文档得知：void clearCache (boolean includeDiskFiles)
参数是true的话除了清理RAM缓存之外还会清理disk的缓存，我个人觉得会造成返回之前的页面时间变长，可能会影响体验。

晚安
